language: java
jdk:
- openjdk11
before_install:
- chmod +x mvnw
deploy:
  provider: heroku
  api_key:
    secure: jVrpJopu661zzPeA2y6ah5XGdoXnnfgx9DuInRBW1re2WVFNThf1d/yYIXzAJ4by7vala9bE8PA1SGTnSNoGmUGV0Txd1pOakL+kYBRI5mEzMraHS7L4P4G+3Bxs9gp5hiTQX7LnaFgiuJdEB3cBzymWHRFoIp7N2rwyOBJJ3zpmTm6/EItJ0JDBcwroD2NrZBES1kD+frV/VdgJ8MNrNpMUcze1HWTe+Wen+SUUId5KxG29MOQGxjG/VHODrZ//agJ63PYqaL6o6TwnM/z6YZ5ES65YQ7WXddDbsbJamLYW4x8RUkdvxMtKGTZhku/smVT7FsAsm2jHoQvR1fGCtl4kIRh+M3GD/uweXdeOiZbTLWUn1qG2wtAMN71LD33AoE7DDQQM5PSZdF2TK/eZSXcpc7B/nnKCkZo5CCvYD7ks78xvAb1LZsnD2gVst41E5auptAfViEUrOR8rRfcvMKRaaiRJ4vwoMKRUlh3vi6izta6smT8eRqpvlHEZRpBLNFqXVvfXHQctJadMEPusS/wL1yr4RVKl2ytcCydkOsyhLCiRVIY2XTut5t9kwwqJKxuKGTDstziOVCySk9mErvswTgT3eeRPtJAMnn4mB/ja1Z5y7YF4SfTxEwEkksG1X+XYDgkkq83FSxIdJoGz1jVGH/G1RYINrjBXLHA+EaI=
  app: legocollectie
